Book_Seller_Website/Areas/Admin/Controllers/UsersController.cs
using Book_Seller_Website.Data;
using Book_Seller_Website.Data.ViewModel;
using Book_Seller_Website.Models.Interface;
using Book_Seller_Website.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Book_Seller_Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UsersController : Controller
    {
        private readonly IUnitOfWork _unit;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(IUnitOfWork unit, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unit = unit;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RoleManagment(string userId)
        {
            RoleManagementVM RoleVM = new RoleManagementVM()
            {
                User = _unit.UserRepository.Get(u => u.Id == userId, includeProperties: "Company"),
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                }),
                CompanyList = _unit.CompanyRepository.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };

            RoleVM.User.Role = _userManager.GetRolesAsync(_unit.UserRepository.Get(u => u.Id == userId))
                    .GetAwaiter().GetResult().FirstOrDefault();
            return View(RoleVM);
        }

        [HttpPost]
        public async Task<IActionResult> RoleManagment([Bind] RoleManagementVM roleVM)
        {
            var user = _unit.UserRepository.Get(x => x.Id == roleVM.User.Id);
            var oldRoles = string.Join(",", await _userManager.GetRolesAsync(user));
            // truong hop 1 user co nhieu role
            //foreach (var roleName in userRoles)
            //{
            //             var role = await _roleManager.FindByNameAsync(roleName);
            //             string oldRole =await _roleManager.GetRoleIdAsync(role);
            //}
            if (!(roleVM.User.Role == oldRoles))
            {
                if (roleVM.User.Role == SD.Role_Company)
                {
                    user.CompanyId = roleVM.User.CompanyId;
                }
                if (oldRoles == SD.Role_Company)
                {
                    // role cu la company, bay gio chuyen sang role khac khong phai company
                    user.CompanyId = null;
                }
                _unit.UserRepository.Update(user);
                _unit.Save();

                await _userManager.RemoveFromRoleAsync(user, oldRoles);
                await _userManager.AddToRoleAsync(user, roleVM.User.Role);
            }
            else
            {
                if (oldRoles != SD.Role_Company)
                {
                    user.CompanyId = roleVM.User.CompanyId;
                }
                _unit.UserRepository.Update(user);
                _unit.Save();
            }
            return RedirectToAction("Index");
        }

        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            List<User> objList = _unit.UserRepository.GetAll(includeProperties: "Company").ToList();

            foreach (var item in objList)
            {
                if (item.CompanyId == null)
                {
                    item.Company = new Company() { Name = "" };
                }
                // han che dung .GetAwaiter().GetResult() 
                // co the dung firstordefault sau usermanager de khong can su dung string.join
                item.Role = string.Join(",", await _userManager.GetRolesAsync(item));
            }
            return Json(new { data = objList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var user = _unit.UserRepository.Get(u => u.Id == id);
            if (user == null)
            {
                return Json(new { success = false, message = "Error while locking/unlocking" });
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(100);
            }
            _unit.UserRepository.Update(user);
            _unit.Save();
            return Json(new { success = true, message = "Lock/Unlock Successful" });
        }
        #endregion
    }
}

Book_Seller_Website/Controllers/CartController.cs
using Book_Seller_Website.Data;
using Book_Seller_Website.Data.ViewModel;
using Book_Seller_Website.Models.Interface;
using Book_Seller_Website.Models.Repository;
using Book_Seller_Website.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;

namespace Book_Seller_Website.Controllers
{
	[Authorize]
	public class CartController : Controller
	{
		[BindProperty]
		public CartVM CartVM { get; set; }
		private readonly IUnitOfWork _unit;
        private readonly IEmailSender _emailSender;
        public CartController(IUnitOfWork unit, IEmailSender emailSender)
		{
			_unit = unit;
			_emailSender = emailSender;

        }
		public IActionResult Index()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			CartVM result = new()
			{
				// co the include them productimage vao day tuy nhien EF se tracking ca nhung entities duoc include
				ListCart = _unit.ShopingCartRepository.GetAll(u => u.Userid == userId, includeProperties: "Product"),
				OrderHeader = new OrderHeader()
			};
            // lay image theo cach thu cong khong su dung include
            var productImages = _unit.ProductImageRepository.GetAll();

            foreach (var item in result.ListCart)
			{
				item.Product.ProductImages = productImages.Where(x => x.ProductId == item.ProductId).ToList();
				item.Price = GetPriceBasedOnQuantity(item);
				result.OrderHeader.OrderTotal += item.Price * item.Count;
			}
			return View(result);
		}

		private double GetPriceBasedOnQuantity(ShopingCart shoppingCart)
		{
			if (shoppingCart.Count <= 50)
			{
				return shoppingCart.Product.Price;
			}
			else
			{
				if (shoppingCart.Count <= 100)
				{
					return shoppingCart.Product.Price50;
				}
				else
				{
					return shoppingCart.Product.Price100;
				}
			}
		}

		public IActionResult Summary()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			CartVM = new()
			{
				ListCart = _unit.ShopingCartRepository.GetAll(u => u.Userid == userId, includeProperties: "Product"),
				OrderHeader = new OrderHeader()
			};
			CartVM.OrderHeader.User = _unit.UserRepository.Get(x => x.Id == userId);

			CartVM.OrderHeader.Name = CartVM.OrderHeader.User.Name;
			CartVM.OrderHeader.PhoneNumber = CartVM.OrderHeader.User.PhoneNumber;
			CartVM.OrderHeader.StreetAddress = CartVM.OrderHeader.User.StreetAddress;
			CartVM.OrderHeader.City = CartVM.OrderHeader.User.City;
			CartVM.OrderHeader.State = CartVM.OrderHeader.User.State;
			CartVM.OrderHeader.PostalCode = CartVM.OrderHeader.User.PostalCode;


			foreach (var item in CartVM.ListCart)
			{
				item.Price = GetPriceBasedOnQuantity(item);
				CartVM.OrderHeader.OrderTotal += item.Price * item.Count;
			}
			return View(CartVM);
		}

		[HttpPost]
		[ActionName("Summary")]
		public IActionResult SummaryPost()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			CartVM.ListCart = _unit.ShopingCartRepository.GetAll(u => u.Userid == userId, includeProperties: "Product");

			CartVM.OrderHeader.Id = 0;
			CartVM.OrderHeader.OrderDate = System.DateTime.Now;
			CartVM.OrderHeader.UserId = userId;

			// cart.OrderHeader.User = _unit.UserRepository.Get(x => x.Id == userId);
			// khong su dung cart.OrderHeader.User vi khi add and save no se hieu nham thanh update do da co userid trong db
			User user = _unit.UserRepository.Get(x => x.Id == userId);
			foreach (var item in CartVM.ListCart)
			{
				item.Price = GetPriceBasedOnQuantity(item);
				CartVM.OrderHeader.OrderTotal += item.Price * item.Count;
			}
			if (user.CompanyId.GetValueOrDefault() == 0)
			{
				// normal customer
				CartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
				CartVM.OrderHeader.OrderStatus = SD.StatusPending;
			}
			else
			{
				// company customer
				CartVM.OrderHeader.PaymentStatus = SD.PaymentStatusDelayedPayment;
				CartVM.OrderHeader.OrderStatus = SD.StatusApproved;
			}
			_unit.OrderHeaderRepository.Add(CartVM.OrderHeader);
			_unit.Save();

			foreach (var item in CartVM.ListCart)
			{
				OrderDetail orderDetails = new()
				{
					ProductId = item.ProductId,
					OrderHeaderId = CartVM.OrderHeader.Id,
					Price = item.Price,
					Count = item.Count
				};
				_unit.OrderDetailRepository.Add(orderDetails);
				_unit.Save();
			}
			if (user.CompanyId.GetValueOrDefault() == 0)
			{
				// stripe payment
				var domain = "https://localhost:7084/";
				var options = new SessionCreateOptions
				{
					SuccessUrl = domain + $"cart/OrderConfirmation?id={CartVM.OrderHeader.Id}",
					CancelUrl = domain + "cart/index",
					LineItems = new List<SessionLineItemOptions>(),
					Mode = "payment",
				};

				foreach (var item in CartVM.ListCart)
				{
					var sessionLineItem = new SessionLineItemOptions
					{
						PriceData = new SessionLineItemPriceDataOptions
						{
							UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
							Currency = "usd",
							ProductData = new SessionLineItemPriceDataProductDataOptions
							{
								Name = item.Product.Title
							}
						},
						Quantity = item.Count
					};
					options.LineItems.Add(sessionLineItem);
				}

				var service = new SessionService();
				Session session = service.Create(options);
				// downgrade stripe package version below 39.199 to add payment intent
				_unit.OrderHeaderRepository.UpdateStripePaymentID(CartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
				_unit.Save();
				Response.Headers.Add("Location", session.Url);
				return new StatusCodeResult(303);

			}

			return RedirectToAction(nameof(OrderConfirmation), new { id = CartVM.OrderHeader.Id });
		}

		public IActionResult OrderConfirmation(int id)
		{
			OrderHeader orderHeader = _unit.OrderHeaderRepository.Get(u => u.Id == id, includeProperties: "User");
			if (orderHeader.PaymentStatus != SD.PaymentStatusDelayedPayment)
			{
				// customer
				var service = new SessionService();
				
				Session session = service.Get(orderHeader.SessionId);

				if (session.PaymentStatus.ToLower() == "paid")
				{
					_unit.OrderHeaderRepository.UpdateStripePaymentID(id, session.Id, session.PaymentIntentId);
					_unit.OrderHeaderRepository.UpdateStatus(id, SD.StatusApproved, SD.PaymentStatusApproved);
					_unit.Save();
				}
				HttpContext.Session.Clear();
			}
            _emailSender.SendEmailAsync(orderHeader.User.Email, "Order Created " + orderHeader.Id.ToString(), "Order has been submitted successfully");
            List<ShopingCart> shoppingCarts = _unit.ShopingCartRepository
			   .GetAll(u => u.Userid == orderHeader.UserId).ToList();
			_unit.ShopingCartRepository.DeleteRange(shoppingCarts);
			_unit.Save();
			return View(id);
		}
		public IActionResult Plus(int id)
		{
			var result = _unit.ShopingCartRepository.Get(x => x.Id == id);
			result.Count += 1;
			_unit.ShopingCartRepository.Update(result);
			_unit.Save();
            return RedirectToAction(nameof(Index));
		}

		public IActionResult Minus(int id)
		{
			var result = _unit.ShopingCartRepository.Get(x => x.Id == id);
			if (result.Count <= 1)
			{
               
                _unit.ShopingCartRepository.Delete(result);
                // neu dat httpcontext len truoc dong xoa thi phai tracking entity bang cach set track = true
                HttpContext.Session.SetInt32(SD.SessionCart, (_unit.ShopingCartRepository.GetAll(x => x.Userid == result.Userid)).Count() - 1);
            }
			else
			{
				result.Count -= 1;
				_unit.ShopingCartRepository.Update(result);
			}
			_unit.Save();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Clear(int id)
		{
			var result = _unit.ShopingCartRepository.Get(x => x.Id == id);
			if (result != null)
			{
				_unit.ShopingCartRepository.Delete(result);
			}
            HttpContext.Session.SetInt32(SD.SessionCart, (_unit.ShopingCartRepository.GetAll(x => x.Userid == result.Userid)).Count()-1);
            _unit.Save();
			return RedirectToAction(nameof(Index));
		}
	}
}

Book_Seller_Website/ViewComponents/ShoppingCartViewComponent.cs
using Book_Seller_Website.Controllers;
using Book_Seller_Website.Models.Interface;
using Book_Seller_Website.Models.Repository;
using Book_Seller_Website.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Book_Seller_Website.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unit;
        public ShoppingCartViewComponent(IUnitOfWork unit)
        {
            _unit = unit;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (userId != null)
            {

                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                    _unit.ShopingCartRepository.GetAll(u => u.Userid == userId.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

Book_Seller_Website/Views/Shared/_Layout.cshtml
@using Book_Seller_Website.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book_Seller_Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Book_Seller_Website.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/book.png" style="width:30px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Orders" asp-action="Index">Manage Order</a>
                        </li>
                        @if(User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Companies" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Manage User</a>
                                    </li>

                                </ul>
                            </li>
                        }
                       
                        <li class="nav-item">
							
                            <a class="nav-link" asp-controller="Cart" asp-action="Index" asp-area="">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                          
                        </li>
                        
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top bg-primary footer text-muted">
            <div class="container text-center">

            &copy; 2023 - Book Seller Website <i class="bi bi-heart-fill"></i> Made By Tung Dao
        </div>
     </footer>
	
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
     <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Book_Seller_Website/Views/Shared/_PartialNotification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}